name: "Setup Expo"
description: "Sets up java 17 and expo env"

inputs:
  expo-token:
    description: 'Expo Token'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    # To avoid the error: _GRADLEW]    > Could not resolve com.google.firebase:firebase-crashlytics-gradle:3.0.0.
    #[RUN_GRADLEW]      Required by:
    #[RUN_GRADLEW]          project :
    #[RUN_GRADLEW]       > Dependency requires at least JVM runtime version 17. This build uses a Java 11 JVM.
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: 🏗 Setup EAS
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ inputs.expo-token }}
        packager: npm
