name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      app--tag_name: ${{ steps.release.outputs.tag_name}}
      app--release_created: ${{ steps.release.outputs.release_created}}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
  release2play-internal-test-track:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{needs.release-please.outputs.app--release_created}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-environment
        with:
          node-version: '20'
          cache-path: 'node_modules'
          cache-key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: npm i
      - uses: ./.github/actions/setup-expo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - name: Build aab
        run: npm run build:android
      - name: Upload to Play Store Internal Testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_CONSOLE_SERVICE_ACCOUNT_JSON }}
          packageName: package.name
          releaseFiles: app-release.aab
          track: internal
          status: draft
          inAppUpdatePriority: 2
  release2testflight:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-environment
        with:
          node-version: '20'
          cache-path: 'node_modules'
          cache-key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: npm i
      - uses: ./.github/actions/setup-expo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          expo-cache: true
          # Create personal access token https://expo.dev/settings/access-tokens
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Build iOS app
        run: eas build --local -p ios --profile production --non-interactive --output app.ipa
      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: './app.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
